# Generated by Django 4.1.7 on 2023-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicardoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unislot',
            name='image',
            field=models.ImageField(height_field=200, max_length=200, upload_to='image', width_field=200),
        ),
    ]
