# Generated by Django 4.1.7 on 2023-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicardoapp', '0002_alter_unislot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unislot',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
